# Site settings
title: DroidJamIndia
email: team@droidjam.in
description: > # this means to ignore newlines until "baseurl:"
  The First edition of the international android conference.
  It is organized annually on a not-for-profit basis by volunteers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://droidjam.in" # the base hostname & protocol for your site
twitter_username: droidjamindia
github_username: droidjamindia
encoding: UTF-8
meta_title: DroidJamIndia - Android conference in India
meta_description: > #
  The First edition of the international android conference.
  It is organized annually on a not-for-profit basis by volunteers.

# Build settings
markdown: kramdown
