baseurl = "https://droidjam.in"
title = "DroidJam"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]
publishDir = "docs"

[params]
  description = "India's premier Android conference"
  logoimage = "images/droidjam.svg"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[languages.en]
languageName = "English"
weight = 1

title = "DroidJam"
description = "India's premier Android conference"
